spring:
  application:
    name: yu-ai-code-mother
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_ai_code_mother
    username: root
    password: 123456
  profiles:
    active: local

server:
  servlet:
    context-path: /api
  port: 8123
# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.yuaicodemother.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
