spring:
  application:
    name: yu-ai-code-mother
server:
  servlet:
    context-path: /api
  port: 8123
# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.yuaicodemother.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
